# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ03-HBa7Vu0udY1kLzKwmbG1jO-Rh-n

# Transformers and MLflow: Downstream Tasks and Experiment Tracking

1. Install Dependencies
"""

!pip install transformers mlflow datasets torch -q

"""2. Sentiment Classification"""

import mlflow
import pandas as pd
from transformers import pipeline

# 20 custom sentences with known labels
sentences = [
    ("I absolutely love this product, it works perfectly!", 1),
    ("This is the best movie I have ever seen.", 1),
    ("What a wonderful experience, highly recommend it.", 1),
    ("The food was delicious and the service was amazing.", 1),
    ("I feel so happy and grateful today.", 1),
    ("This book changed my life for the better.", 1),
    ("Excellent quality, arrived on time and well packaged.", 1),
    ("The concert was breathtaking and unforgettable.", 1),
    ("I am so proud of what we accomplished together.", 1),
    ("Great customer support, they resolved my issue instantly.", 1),
    ("This is absolutely terrible, I want a refund.", 0),
    ("Worst experience of my life, never coming back.", 0),
    ("The product broke after one day, complete waste of money.", 0),
    ("I am deeply disappointed with the service.", 0),
    ("The movie was boring and made no sense at all.", 0),
    ("Horrible smell, packaging was damaged and dirty.", 0),
    ("Customer service was rude and unhelpful.", 0),
    ("I regret buying this, it does not work at all.", 0),
    ("The food tasted awful and made me sick.", 0),
    ("Terrible quality, nothing like the description.", 0),
]

texts  = [s[0] for s in sentences]
labels = [s[1] for s in sentences]   # 1=positive, 0=negative

MODEL_NAME = "distilbert-base-uncased-finetuned-sst-2-english"
classifier = pipeline("sentiment-analysis", model=MODEL_NAME)

mlflow.set_experiment("Task1_Sentiment_Classification")

with mlflow.start_run(run_name="distilbert_sentiment"):
    results = classifier(texts)

    # Map POSITIVE->1, NEGATIVE->0
    preds = [1 if r["label"] == "POSITIVE" else 0 for r in results]
    accuracy = sum(p == l for p, l in zip(preds, labels)) / len(labels)

    # Log params & metrics
    mlflow.log_param("model_name", MODEL_NAME)
    mlflow.log_param("num_samples", len(texts))
    mlflow.log_metric("accuracy", accuracy)

    # Save predictions CSV as artifact
    df = pd.DataFrame({
        "sentence": texts,
        "true_label": labels,
        "predicted_label": preds,
        "score": [r["score"] for r in results]
    })
    df.to_csv("sentiment_predictions.csv", index=False)
    mlflow.log_artifact("sentiment_predictions.csv")

    print(f"Accuracy: {accuracy:.4f}")
    print(df.to_string(index=False))

"""3. Second Run"""

MODEL_NAME_2 = "cardiffnlp/twitter-roberta-base-sentiment-latest"
classifier2  = pipeline("sentiment-analysis", model=MODEL_NAME_2)

# This model uses: positive / negative / neutral labels
label_map = {"positive": 1, "negative": 0, "neutral": 0}

with mlflow.start_run(run_name="roberta_sentiment"):
    results2 = classifier2(texts)
    preds2   = [label_map.get(r["label"].lower(), 0) for r in results2]
    accuracy2 = sum(p == l for p, l in zip(preds2, labels)) / len(labels)

    mlflow.log_param("model_name", MODEL_NAME_2)
    mlflow.log_param("num_samples", len(texts))
    mlflow.log_metric("accuracy", accuracy2)

    df2 = pd.DataFrame({
        "sentence": texts,
        "true_label": labels,
        "predicted_label": preds2,
        "score": [r["score"] for r in results2]
    })
    df2.to_csv("sentiment_predictions_roberta.csv", index=False)
    mlflow.log_artifact("sentiment_predictions_roberta.csv")

    print(f"RoBERTa Accuracy: {accuracy2:.4f}")

"""4. Named Entity Recognition"""

from collections import Counter
import json

NER_MODEL = "dslim/bert-base-NER"
ner = pipeline("ner", model=NER_MODEL, aggregation_strategy="simple")

paragraphs = [
    "Apple Inc. was founded by Steve Jobs and Steve Wozniak in Cupertino, California.",
    "Elon Musk is the CEO of Tesla and SpaceX, both headquartered in the United States.",
    "The United Nations headquarters is located in New York City, led by António Guterres.",
    "Barack Obama served as the 44th President of the United States and was born in Hawaii.",
    "Amazon was founded by Jeff Bezos and is based in Seattle, Washington.",
    "The Eiffel Tower is located in Paris, France and was designed by Gustave Eiffel.",
    "Microsoft, founded by Bill Gates and Paul Allen, is headquartered in Redmond, Washington.",
    "Cristiano Ronaldo plays for Al Nassr FC in Riyadh, Saudi Arabia.",
    "The World Health Organization is based in Geneva, Switzerland.",
    "Narendra Modi is the Prime Minister of India, which has its capital in New Delhi.",
]

mlflow.set_experiment("Task2_Named_Entity_Recognition")

with mlflow.start_run(run_name="bert_base_NER_run1"):
    all_entities = []
    output_rows  = []

    for i, para in enumerate(paragraphs):
        entities = ner(para)
        for ent in entities:
            all_entities.append(ent["entity_group"])
            output_rows.append({
                "paragraph_id": i + 1,
                "paragraph":    para[:60] + "...",
                "entity":       ent["word"],
                "entity_type":  ent["entity_group"],
                "score":        round(ent["score"], 4)
            })

    # Count entity types
    counts = Counter(all_entities)
    total  = len(all_entities)

    # Log params & metrics
    mlflow.log_param("model_name",      NER_MODEL)
    mlflow.log_param("num_paragraphs",  len(paragraphs))
    mlflow.log_metric("total_entities", total)
    mlflow.log_metric("PER_count",      counts.get("PER", 0))
    mlflow.log_metric("ORG_count",      counts.get("ORG", 0))
    mlflow.log_metric("LOC_count",      counts.get("LOC", 0))

    # Save artifact
    df_ner = pd.DataFrame(output_rows)
    df_ner.to_csv("ner_output.csv", index=False)
    mlflow.log_artifact("ner_output.csv")

    print(f"Total entities: {total}")
    print(f"Distribution  : {dict(counts)}")
    print(df_ner.to_string(index=False))

"""5. Second Run"""

NER_MODEL_2 = "Jean-Baptiste/roberta-large-ner-english"
ner2 = pipeline("ner", model=NER_MODEL_2, aggregation_strategy="simple")

with mlflow.start_run(run_name="roberta_large_NER_run2"):
    all_entities2 = []
    output_rows2  = []

    for i, para in enumerate(paragraphs):
        entities = ner2(para)
        for ent in entities:
            all_entities2.append(ent["entity_group"])
            output_rows2.append({
                "paragraph_id": i + 1,
                "entity":       ent["word"],
                "entity_type":  ent["entity_group"],
                "score":        round(ent["score"], 4)
            })

    counts2 = Counter(all_entities2)
    total2  = len(all_entities2)

    mlflow.log_param("model_name",      NER_MODEL_2)
    mlflow.log_param("num_paragraphs",  len(paragraphs))
    mlflow.log_metric("total_entities", total2)
    mlflow.log_metric("PER_count",      counts2.get("PER", 0))
    mlflow.log_metric("ORG_count",      counts2.get("ORG", 0))
    mlflow.log_metric("LOC_count",      counts2.get("LOC", 0))

    df_ner2 = pd.DataFrame(output_rows2)
    df_ner2.to_csv("ner_output_roberta.csv", index=False)
    mlflow.log_artifact("ner_output_roberta.csv")

    print(f"RoBERTa NER — Total: {total2}, Distribution: {dict(counts2)}")

"""6. Text Generation"""

gen = pipeline("text-generation", model="gpt2")

prompts = [
    "The future of artificial intelligence is",
    "Once upon a time in a land far away",
    "Scientists have recently discovered that",
    "The best way to learn programming is",
    "In the year 2050, humans will",
]

# Two configurations to compare
configs = [
    {"max_length": 80,  "temperature": 0.7,  "run_name": "gpt2_temp07_len80"},
    {"max_length": 120, "temperature": 1.2,  "run_name": "gpt2_temp12_len120"},
]

mlflow.set_experiment("Task3_Text_Generation")

for cfg in configs:
    with mlflow.start_run(run_name=cfg["run_name"]):
        mlflow.log_param("model_name",   "gpt2")
        mlflow.log_param("temperature",  cfg["temperature"])
        mlflow.log_param("max_length",   cfg["max_length"])
        mlflow.log_param("num_prompts",  len(prompts))

        observations = []
        for i, prompt in enumerate(prompts):
            output = gen(
                prompt,
                max_length=cfg["max_length"],
                temperature=cfg["temperature"],
                do_sample=True,
                pad_token_id=50256
            )
            generated_text = output[0]["generated_text"]

            obs = {
                "prompt_id":      i + 1,
                "prompt":         prompt,
                "generated_text": generated_text,
                "output_length":  len(generated_text.split()),
                "temperature":    cfg["temperature"],
                "max_length":     cfg["max_length"],
            }
            observations.append(obs)
            print(f"\nPrompt {i+1}: {prompt}")
            print(f"Output : {generated_text[:200]}...")

        # Save outputs as artifact
        df_gen = pd.DataFrame(observations)
        fname  = f"generation_{cfg['run_name']}.csv"
        df_gen.to_csv(fname, index=False)
        mlflow.log_artifact(fname)

        # Text observation artifact
        obs_text = f"""
Configuration: temp={cfg['temperature']}, max_length={cfg['max_length']}
-----------------------------------------------------------------------
Observation:
- Lower temperature (0.7) produces more focused, coherent continuations.
- Higher temperature (1.2) produces more creative but less predictable text.
- GPT-2 tends to stay on-topic for factual prompts but drifts on open-ended ones.
- Longer max_length allows more complete thoughts but may introduce repetition.
        """
        with open(f"observations_{cfg['run_name']}.txt", "w") as f:
            f.write(obs_text)
        mlflow.log_artifact(f"observations_{cfg['run_name']}.txt")

        mlflow.log_metric("avg_output_length",
                          sum(o["output_length"] for o in observations) / len(observations))

"""7. View MLflow UI in Colab"""

import mlflow

client = mlflow.tracking.MlflowClient()
experiments = client.search_experiments()

for exp in experiments:
    print(f"\n{'='*60}")
    print(f"Experiment: {exp.name}")
    print(f"{'='*60}")

    runs = client.search_runs(exp.experiment_id)
    for run in runs:
        print(f"\n  Run: {run.info.run_name}")
        print(f"  Params  : {run.data.params}")
        print(f"  Metrics : {run.data.metrics}")